/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminProposalsRouteImport } from './routes/admin.proposals'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ProposalProposalIdRouteImport } from './routes/proposal.$proposalId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProposalsRoute = AdminProposalsRouteImport.update({
  id: '/admin/proposals',
  path: '/admin/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalProposalIdRoute = ProposalProposalIdRouteImport.update({
  id: '/proposal/$proposalId',
  path: '/proposal/$proposalId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/proposals': typeof AdminProposalsRoute
  '/api/chat': typeof ApiChatRoute
  '/proposal/$proposalId': typeof ProposalProposalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/proposals': typeof AdminProposalsRoute
  '/api/chat': typeof ApiChatRoute
  '/proposal/$proposalId': typeof ProposalProposalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/proposals': typeof AdminProposalsRoute
  '/api/chat': typeof ApiChatRoute
  '/proposal/$proposalId': typeof ProposalProposalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/proposals' | '/api/chat' | '/proposal/$proposalId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/proposals' | '/api/chat' | '/proposal/$proposalId'
  id:
    | '__root__'
    | '/'
    | '/admin/proposals'
    | '/api/chat'
    | '/proposal/$proposalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminProposalsRoute: typeof AdminProposalsRoute
  ApiChatRoute: typeof ApiChatRoute
  ProposalProposalIdRoute: typeof ProposalProposalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/proposals': {
      id: '/admin/proposals'
      path: '/admin/proposals'
      fullPath: '/admin/proposals'
      preLoaderRoute: typeof AdminProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal/$proposalId': {
      id: '/proposal/$proposalId'
      path: '/proposal/$proposalId'
      fullPath: '/proposal/$proposalId'
      preLoaderRoute: typeof ProposalProposalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminProposalsRoute: AdminProposalsRoute,
  ApiChatRoute: ApiChatRoute,
  ProposalProposalIdRoute: ProposalProposalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
